CREATE DATABASE maystore;

USE maystore;

CREATE TABLE CLIENTE (
    CLI_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLI_NOMECOMPLETO VARCHAR(150) NOT NULL,
    CLI_CPF VARCHAR(20) NOT NULL
);

CREATE TABLE ENDERECO (
    END_ID INT AUTO_INCREMENT PRIMARY KEY,
    END_CLI_ID INT NOT NULL,
    END_ENDERECO VARCHAR(200) NOT NULL,
    END_CIDADE VARCHAR(100),
    END_CEP VARCHAR(20),
    END_ESTADO VARCHAR(30),
    FOREIGN KEY (END_CLI_ID) REFERENCES CLIENTE(CLI_ID)
);

CREATE TABLE CONTATO (
    CON_ID INT AUTO_INCREMENT PRIMARY KEY,
    CON_CLI_ID INT NOT NULL,
    CON_TELEFONE VARCHAR(20) NOT NULL,
    CON_NOMECONTATO VARCHAR(50),
    FOREIGN KEY (CON_CLI_ID) REFERENCES CLIENTE(CLI_ID)
);

CREATE TABLE PRODUTO (
    PRO_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRO_CODIGOFORNECEDOR VARCHAR(50),
    PRO_DATACADASTRO DATE NOT NULL DEFAULT CURRENT_DATE(),
    PRO_TIPO VARCHAR(20) NOT NULL,
    PRO_DESCRICAO VARCHAR(200) NOT NULL,
    PRO_QUANTIDADE INT NOT NULL DEFAULT 0,
    PRO_UNIDADE VARCHAR(20),
    PRO_TAMANHO VARCHAR(10),
    PRO_MODELO VARCHAR(50),
    PRO_MARCA VARCHAR(50),
    PRO_IMAGEM TEXT,
    PRO_VALORCOMPRA DECIMAL(10,2) NOT NULL,
    PRO_VALORVENDA DECIMAL(10,2) NOT NULL
);

CREATE TABLE VENDA (
    VEN_ID INT AUTO_INCREMENT PRIMARY KEY,
    VEN_DATAVENDA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    VEN_CLI_ID INT NOT NULL,
    VEN_FORMAPAGAMENTO VARCHAR(20) NOT NULL, 
    VEN_PARCELAS INT, 
    VEN_SUBTOTAL DECIMAL(10,2) NOT NULL,
    VEN_DESCONTO DECIMAL(10,2) DEFAULT 0,
    VEN_TOTAL DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (VEN_CLI_ID) REFERENCES CLIENTE(CLI_ID)
);

CREATE TABLE ITENSVENDA (
    ITV_ID INT AUTO_INCREMENT PRIMARY KEY,
    ITV_VEN_ID INT NOT NULL,
    ITV_PRO_ID INT NOT NULL,
    ITV_QUANTIDADE INT NOT NULL,
    ITV_PRECOUNITARIO DECIMAL(10,2) NOT NULL,
    
    
    FOREIGN KEY (ITV_VEN_ID) REFERENCES VENDA(VEN_ID),
    FOREIGN KEY (ITV_PRO_ID) REFERENCES PRODUTO(PRO_ID)
);

